package POJO;
// Generated Jan 6, 2012 10:51:52 PM by Hibernate Tools 3.2.1.GA



/**
 * Danhgiasanpham generated by hbm2java
 */
public class Danhgiasanpham  implements java.io.Serializable {


     private Integer maDanhGiaSanPham;
     private Khachhang khachhang;
     private Sanpham sanpham;
     private Integer diemDanhGia;

    public Danhgiasanpham() {
    }

    public Danhgiasanpham(Khachhang khachhang, Sanpham sanpham, Integer diemDanhGia) {
       this.khachhang = khachhang;
       this.sanpham = sanpham;
       this.diemDanhGia = diemDanhGia;
    }
   
    public Integer getMaDanhGiaSanPham() {
        return this.maDanhGiaSanPham;
    }
    
    public void setMaDanhGiaSanPham(Integer maDanhGiaSanPham) {
        this.maDanhGiaSanPham = maDanhGiaSanPham;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Sanpham getSanpham() {
        return this.sanpham;
    }
    
    public void setSanpham(Sanpham sanpham) {
        this.sanpham = sanpham;
    }
    public Integer getDiemDanhGia() {
        return this.diemDanhGia;
    }
    
    public void setDiemDanhGia(Integer diemDanhGia) {
        this.diemDanhGia = diemDanhGia;
    }




}


