package POJO;
// Generated Dec 3, 2011 10:29:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dondathang generated by hbm2java
 */
public class Dondathang  implements java.io.Serializable {


     private Integer maDonDatHang;
     private Khachhang khachhang;
     private Tinhtrangdondathang tinhtrangdondathang;
     private Date ngayDatHang;
     private Set chitietdondathangs = new HashSet(0);

    public Dondathang() {
    }

    public Dondathang(Khachhang khachhang, Tinhtrangdondathang tinhtrangdondathang, Date ngayDatHang, Set chitietdondathangs) {
       this.khachhang = khachhang;
       this.tinhtrangdondathang = tinhtrangdondathang;
       this.ngayDatHang = ngayDatHang;
       this.chitietdondathangs = chitietdondathangs;
    }
   
    public Integer getMaDonDatHang() {
        return this.maDonDatHang;
    }
    
    public void setMaDonDatHang(Integer maDonDatHang) {
        this.maDonDatHang = maDonDatHang;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Tinhtrangdondathang getTinhtrangdondathang() {
        return this.tinhtrangdondathang;
    }
    
    public void setTinhtrangdondathang(Tinhtrangdondathang tinhtrangdondathang) {
        this.tinhtrangdondathang = tinhtrangdondathang;
    }
    public Date getNgayDatHang() {
        return this.ngayDatHang;
    }
    
    public void setNgayDatHang(Date ngayDatHang) {
        this.ngayDatHang = ngayDatHang;
    }
    public Set getChitietdondathangs() {
        return this.chitietdondathangs;
    }
    
    public void setChitietdondathangs(Set chitietdondathangs) {
        this.chitietdondathangs = chitietdondathangs;
    }




}


