package POJO;
// Generated Jan 2, 2012 10:31:44 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Dondathang generated by hbm2java
 */
public class Dondathang  implements java.io.Serializable {


     private Integer maDonDatHang;
     private Khachhang khachhang;
     private Tinhtrangdondathang tinhtrangdondathang;
     private Tinhtrang tinhtrang;
     private String ngayDatHang;
     private String hinhThucMuaHang;
     private String diaDiemGiaoHang;
     private Float tongTien;
     private Set chitietdondathangs = new HashSet(0);

    public Dondathang() {
    }

    public Dondathang(Khachhang khachhang, Tinhtrangdondathang tinhtrangdondathang, Tinhtrang tinhtrang, String ngayDatHang, String hinhThucMuaHang, String diaDiemGiaoHang, Float tongTien, Set chitietdondathangs) {
       this.khachhang = khachhang;
       this.tinhtrangdondathang = tinhtrangdondathang;
       this.tinhtrang = tinhtrang;
       this.ngayDatHang = ngayDatHang;
       this.hinhThucMuaHang = hinhThucMuaHang;
       this.diaDiemGiaoHang = diaDiemGiaoHang;
       this.tongTien = tongTien;
       this.chitietdondathangs = chitietdondathangs;
    }
   
    public Integer getMaDonDatHang() {
        return this.maDonDatHang;
    }
    
    public void setMaDonDatHang(Integer maDonDatHang) {
        this.maDonDatHang = maDonDatHang;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Tinhtrangdondathang getTinhtrangdondathang() {
        return this.tinhtrangdondathang;
    }
    
    public void setTinhtrangdondathang(Tinhtrangdondathang tinhtrangdondathang) {
        this.tinhtrangdondathang = tinhtrangdondathang;
    }
    public Tinhtrang getTinhtrang() {
        return this.tinhtrang;
    }
    
    public void setTinhtrang(Tinhtrang tinhtrang) {
        this.tinhtrang = tinhtrang;
    }
    public String getNgayDatHang() {
        return this.ngayDatHang;
    }
    
    public void setNgayDatHang(String ngayDatHang) {
        this.ngayDatHang = ngayDatHang;
    }
    public String getHinhThucMuaHang() {
        return this.hinhThucMuaHang;
    }
    
    public void setHinhThucMuaHang(String hinhThucMuaHang) {
        this.hinhThucMuaHang = hinhThucMuaHang;
    }
    public String getDiaDiemGiaoHang() {
        return this.diaDiemGiaoHang;
    }
    
    public void setDiaDiemGiaoHang(String diaDiemGiaoHang) {
        this.diaDiemGiaoHang = diaDiemGiaoHang;
    }
    public Float getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(Float tongTien) {
        this.tongTien = tongTien;
    }
    public Set getChitietdondathangs() {
        return this.chitietdondathangs;
    }
    
    public void setChitietdondathangs(Set chitietdondathangs) {
        this.chitietdondathangs = chitietdondathangs;
    }




}


