package POJO;
// Generated Jan 1, 2012 11:48:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hangsanxuat generated by hbm2java
 */
public class Hangsanxuat  implements java.io.Serializable {


     private Integer maHangSanXuat;
     private String tenHangSanXuat;
     private Boolean uuTien;
     private Set sanphams = new HashSet(0);

    public Hangsanxuat() {
    }

    public Hangsanxuat(String tenHangSanXuat, Boolean uuTien, Set sanphams) {
       this.tenHangSanXuat = tenHangSanXuat;
       this.uuTien = uuTien;
       this.sanphams = sanphams;
    }
   
    public Integer getMaHangSanXuat() {
        return this.maHangSanXuat;
    }
    
    public void setMaHangSanXuat(Integer maHangSanXuat) {
        this.maHangSanXuat = maHangSanXuat;
    }
    public String getTenHangSanXuat() {
        return this.tenHangSanXuat;
    }
    
    public void setTenHangSanXuat(String tenHangSanXuat) {
        this.tenHangSanXuat = tenHangSanXuat;
    }
    public Boolean getUuTien() {
        return this.uuTien;
    }
    
    public void setUuTien(Boolean uuTien) {
        this.uuTien = uuTien;
    }
    public Set getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set sanphams) {
        this.sanphams = sanphams;
    }




}


