package POJO;
// Generated Nov 22, 2011 12:52:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hinhanh generated by hbm2java
 */
public class Hinhanh  implements java.io.Serializable {


     private Integer maHinhAnh;
     private String anhNho;
     private String anhTo1;
     private String anhTo2;
     private String anhTo3;
     private String anhTo4;
     private Set sanphams = new HashSet(0);

    public Hinhanh() {
    }

    public Hinhanh(String anhNho, String anhTo1, String anhTo2, String anhTo3, String anhTo4, Set sanphams) {
       this.anhNho = anhNho;
       this.anhTo1 = anhTo1;
       this.anhTo2 = anhTo2;
       this.anhTo3 = anhTo3;
       this.anhTo4 = anhTo4;
       this.sanphams = sanphams;
    }
   
    public Integer getMaHinhAnh() {
        return this.maHinhAnh;
    }
    
    public void setMaHinhAnh(Integer maHinhAnh) {
        this.maHinhAnh = maHinhAnh;
    }
    public String getAnhNho() {
        return this.anhNho;
    }
    
    public void setAnhNho(String anhNho) {
        this.anhNho = anhNho;
    }
    public String getAnhTo1() {
        return this.anhTo1;
    }
    
    public void setAnhTo1(String anhTo1) {
        this.anhTo1 = anhTo1;
    }
    public String getAnhTo2() {
        return this.anhTo2;
    }
    
    public void setAnhTo2(String anhTo2) {
        this.anhTo2 = anhTo2;
    }
    public String getAnhTo3() {
        return this.anhTo3;
    }
    
    public void setAnhTo3(String anhTo3) {
        this.anhTo3 = anhTo3;
    }
    public String getAnhTo4() {
        return this.anhTo4;
    }
    
    public void setAnhTo4(String anhTo4) {
        this.anhTo4 = anhTo4;
    }
    public Set getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set sanphams) {
        this.sanphams = sanphams;
    }




}


