package POJO;
// Generated Dec 3, 2011 10:29:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Loaisanpham generated by hbm2java
 */
public class Loaisanpham  implements java.io.Serializable {


     private Integer maLoaiSanPham;
     private Nhomsanpham nhomsanpham;
     private Tinhtrang tinhtrang;
     private String tenLoaiSanPham;
     private Date ngayCongBo;
     private Set sanphams = new HashSet(0);

    public Loaisanpham() {
    }

    public Loaisanpham(Nhomsanpham nhomsanpham, Tinhtrang tinhtrang, String tenLoaiSanPham, Date ngayCongBo, Set sanphams) {
       this.nhomsanpham = nhomsanpham;
       this.tinhtrang = tinhtrang;
       this.tenLoaiSanPham = tenLoaiSanPham;
       this.ngayCongBo = ngayCongBo;
       this.sanphams = sanphams;
    }
   
    public Integer getMaLoaiSanPham() {
        return this.maLoaiSanPham;
    }
    
    public void setMaLoaiSanPham(Integer maLoaiSanPham) {
        this.maLoaiSanPham = maLoaiSanPham;
    }
    public Nhomsanpham getNhomsanpham() {
        return this.nhomsanpham;
    }
    
    public void setNhomsanpham(Nhomsanpham nhomsanpham) {
        this.nhomsanpham = nhomsanpham;
    }
    public Tinhtrang getTinhtrang() {
        return this.tinhtrang;
    }
    
    public void setTinhtrang(Tinhtrang tinhtrang) {
        this.tinhtrang = tinhtrang;
    }
    public String getTenLoaiSanPham() {
        return this.tenLoaiSanPham;
    }
    
    public void setTenLoaiSanPham(String tenLoaiSanPham) {
        this.tenLoaiSanPham = tenLoaiSanPham;
    }
    public Date getNgayCongBo() {
        return this.ngayCongBo;
    }
    
    public void setNgayCongBo(Date ngayCongBo) {
        this.ngayCongBo = ngayCongBo;
    }
    public Set getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set sanphams) {
        this.sanphams = sanphams;
    }




}


