package POJO;
// Generated Nov 22, 2011 9:57:02 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Loaimathang generated by hbm2java
 */
public class Loaimathang  implements java.io.Serializable {


     private Integer maLoaiMatHang;
     private Tinhtrang tinhtrang;
     private String tenLoaiMatHang;
     private Date ngayCongBo;

    public Loaimathang() {
    }

    public Loaimathang(Tinhtrang tinhtrang, String tenLoaiMatHang, Date ngayCongBo) {
       this.tinhtrang = tinhtrang;
       this.tenLoaiMatHang = tenLoaiMatHang;
       this.ngayCongBo = ngayCongBo;
    }
   
    public Integer getMaLoaiMatHang() {
        return this.maLoaiMatHang;
    }
    
    public void setMaLoaiMatHang(Integer maLoaiMatHang) {
        this.maLoaiMatHang = maLoaiMatHang;
    }
    public Tinhtrang getTinhtrang() {
        return this.tinhtrang;
    }
    
    public void setTinhtrang(Tinhtrang tinhtrang) {
        this.tinhtrang = tinhtrang;
    }
    public String getTenLoaiMatHang() {
        return this.tenLoaiMatHang;
    }
    
    public void setTenLoaiMatHang(String tenLoaiMatHang) {
        this.tenLoaiMatHang = tenLoaiMatHang;
    }
    public Date getNgayCongBo() {
        return this.ngayCongBo;
    }
    
    public void setNgayCongBo(Date ngayCongBo) {
        this.ngayCongBo = ngayCongBo;
    }




}


