package POJO;
// Generated Dec 3, 2011 10:29:11 AM by Hibernate Tools 3.2.1.GA


import DAO.HangSanXuatDAO;
import DAO.LoaiSanPhamDAO;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sanpham generated by hbm2java
 */
public class Sanpham  implements java.io.Serializable {


     private Integer maSanPham;
     private Hangsanxuat hangsanxuat;
     private Tinhtrang tinhtrang;
     private Loaisanpham loaisanpham;
     private String tenSanPham;
     private Float giaGoc;
     private Float giamGia;
     private Integer danhGia;
     private Date ngayHetHan;
     private Integer soLuong;
     private String moTa;
     private String thongTinChiTiet;
     private Integer soHinhAnh;
     private Set chitietdondathangs = new HashSet(0);
     private Set binhluans = new HashSet(0);

    public Sanpham() {
    }

    public Sanpham(Hangsanxuat hangsanxuat, Tinhtrang tinhtrang, Loaisanpham loaisanpham, String tenSanPham, Float giaGoc, Float giamGia, Integer danhGia, Date ngayHetHan, Integer soLuong, String moTa, String thongTinChiTiet, Integer soHinhAnh, Set chitietdondathangs, Set binhluans) {
       this.hangsanxuat = hangsanxuat;
       this.tinhtrang = tinhtrang;
       this.loaisanpham = loaisanpham;
       this.tenSanPham = tenSanPham;
       this.giaGoc = giaGoc;
       this.giamGia = giamGia;
       this.danhGia = danhGia;
       this.ngayHetHan = ngayHetHan;
       this.soLuong = soLuong;
       this.moTa = moTa;
       this.thongTinChiTiet = thongTinChiTiet;
       this.soHinhAnh = soHinhAnh;
       this.chitietdondathangs = chitietdondathangs;
       this.binhluans = binhluans;
    }
   
    public Integer getMaSanPham() {
        return this.maSanPham;
    }
    
    public void setMaSanPham(Integer maSanPham) {
        this.maSanPham = maSanPham;
    }
    public Hangsanxuat getHangsanxuat() {
        return this.hangsanxuat;
    }
    
    public void setHangsanxuat(Hangsanxuat hangsanxuat) {
        this.hangsanxuat = hangsanxuat;
    }
    public Tinhtrang getTinhtrang() {
        return this.tinhtrang;
    }
    
    public void setTinhtrang(Tinhtrang tinhtrang) {
        this.tinhtrang = tinhtrang;
    }
    public Loaisanpham getLoaisanpham() {
        return this.loaisanpham;
    }
    
    public void setLoaisanpham(Loaisanpham loaisanpham) {
        this.loaisanpham = loaisanpham;
    }
    public String getTenSanPham() {
        return this.tenSanPham;
    }
    
    public void setTenSanPham(String tenSanPham) {
        this.tenSanPham = tenSanPham;
    }
    public Float getGiaGoc() {
        return this.giaGoc;
    }
    
    public void setGiaGoc(Float giaGoc) {
        this.giaGoc = giaGoc;
    }
    public Float getGiamGia() {
        return this.giamGia;
    }
    
    public void setGiamGia(Float giamGia) {
        this.giamGia = giamGia;
    }
    public Integer getDanhGia() {
        return this.danhGia;
    }
    
    public void setDanhGia(Integer danhGia) {
        this.danhGia = danhGia;
    }
    public Date getNgayHetHan() {
        return this.ngayHetHan;
    }
    
    public void setNgayHetHan(Date ngayHetHan) {
        this.ngayHetHan = ngayHetHan;
    }
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }
    public String getThongTinChiTiet() {
        return this.thongTinChiTiet;
    }
    
    public void setThongTinChiTiet(String thongTinChiTiet) {
        this.thongTinChiTiet = thongTinChiTiet;
    }
    public Integer getSoHinhAnh() {
        return this.soHinhAnh;
    }
    
    public void setSoHinhAnh(Integer soHinhAnh) {
        this.soHinhAnh = soHinhAnh;
    }
    public Set getChitietdondathangs() {
        return this.chitietdondathangs;
    }
    
    public void setChitietdondathangs(Set chitietdondathangs) {
        this.chitietdondathangs = chitietdondathangs;
    }
    public Set getBinhluans() {
        return this.binhluans;
    }
    
    public void setBinhluans(Set binhluans) {
        this.binhluans = binhluans;
    }

//them vao
    public String getTenHangSX()
    {
        return HangSanXuatDAO.LayHangSanXuatTheoMa(hangsanxuat.getMaHangSanXuat()).getTenHangSanXuat();
    }
    public String getTenLoaiSanPham()
    {
        return LoaiSanPhamDAO.LayLoaiSanPhamTheoMa(loaisanpham.getMaLoaiSanPham()).getTenLoaiSanPham();
    }
    public int getMaTinhTrang()
    {
        return tinhtrang.getMaTinhTrang();
    }

}


