package POJO;
// Generated Jan 2, 2012 5:03:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tinhtrangdondathang generated by hbm2java
 */
public class Tinhtrangdondathang  implements java.io.Serializable {


     private int maTinhTrangDonDatHang;
     private String tenTinhTrangDonDatHang;
     private Set dondathangs = new HashSet(0);

    public Tinhtrangdondathang() {
    }

	
    public Tinhtrangdondathang(int maTinhTrangDonDatHang) {
        this.maTinhTrangDonDatHang = maTinhTrangDonDatHang;
    }
    public Tinhtrangdondathang(int maTinhTrangDonDatHang, String tenTinhTrangDonDatHang, Set dondathangs) {
       this.maTinhTrangDonDatHang = maTinhTrangDonDatHang;
       this.tenTinhTrangDonDatHang = tenTinhTrangDonDatHang;
       this.dondathangs = dondathangs;
    }
   
    public int getMaTinhTrangDonDatHang() {
        return this.maTinhTrangDonDatHang;
    }
    
    public void setMaTinhTrangDonDatHang(int maTinhTrangDonDatHang) {
        this.maTinhTrangDonDatHang = maTinhTrangDonDatHang;
    }
    public String getTenTinhTrangDonDatHang() {
        return this.tenTinhTrangDonDatHang;
    }
    
    public void setTenTinhTrangDonDatHang(String tenTinhTrangDonDatHang) {
        this.tenTinhTrangDonDatHang = tenTinhTrangDonDatHang;
    }
    public Set getDondathangs() {
        return this.dondathangs;
    }
    
    public void setDondathangs(Set dondathangs) {
        this.dondathangs = dondathangs;
    }




}


