package POJO;
// Generated Nov 22, 2011 9:57:02 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tinhtrang generated by hbm2java
 */
public class Tinhtrang  implements java.io.Serializable {


     private Integer maTinhTrang;
     private String tenTinhTrang;
     private Set loaimathangs = new HashSet(0);

    public Tinhtrang() {
    }

    public Tinhtrang(String tenTinhTrang, Set loaimathangs) {
       this.tenTinhTrang = tenTinhTrang;
       this.loaimathangs = loaimathangs;
    }
   
    public Integer getMaTinhTrang() {
        return this.maTinhTrang;
    }
    
    public void setMaTinhTrang(Integer maTinhTrang) {
        this.maTinhTrang = maTinhTrang;
    }
    public String getTenTinhTrang() {
        return this.tenTinhTrang;
    }
    
    public void setTenTinhTrang(String tenTinhTrang) {
        this.tenTinhTrang = tenTinhTrang;
    }
    public Set getLoaimathangs() {
        return this.loaimathangs;
    }
    
    public void setLoaimathangs(Set loaimathangs) {
        this.loaimathangs = loaimathangs;
    }




}


