package POJO;
// Generated Dec 3, 2011 10:29:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tinhtrang generated by hbm2java
 */
public class Tinhtrang  implements java.io.Serializable {


     private Integer maTinhTrang;
     private String tenTinhTrang;
     private Set sanphams = new HashSet(0);
     private Set loaisanphams = new HashSet(0);
     private Set chitietdondathangs = new HashSet(0);
     private Set nhomsanphams = new HashSet(0);

    public Tinhtrang() {
    }

    public Tinhtrang(String tenTinhTrang, Set sanphams, Set loaisanphams, Set chitietdondathangs, Set nhomsanphams) {
       this.tenTinhTrang = tenTinhTrang;
       this.sanphams = sanphams;
       this.loaisanphams = loaisanphams;
       this.chitietdondathangs = chitietdondathangs;
       this.nhomsanphams = nhomsanphams;
    }
   
    public Integer getMaTinhTrang() {
        return this.maTinhTrang;
    }
    
    public void setMaTinhTrang(Integer maTinhTrang) {
        this.maTinhTrang = maTinhTrang;
    }
    public String getTenTinhTrang() {
        return this.tenTinhTrang;
    }
    
    public void setTenTinhTrang(String tenTinhTrang) {
        this.tenTinhTrang = tenTinhTrang;
    }
    public Set getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set sanphams) {
        this.sanphams = sanphams;
    }
    public Set getLoaisanphams() {
        return this.loaisanphams;
    }
    
    public void setLoaisanphams(Set loaisanphams) {
        this.loaisanphams = loaisanphams;
    }
    public Set getChitietdondathangs() {
        return this.chitietdondathangs;
    }
    
    public void setChitietdondathangs(Set chitietdondathangs) {
        this.chitietdondathangs = chitietdondathangs;
    }
    public Set getNhomsanphams() {
        return this.nhomsanphams;
    }
    
    public void setNhomsanphams(Set nhomsanphams) {
        this.nhomsanphams = nhomsanphams;
    }




}


