//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace RemoteObjectEngine.nvvQLTMN_BUS_WS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LayDanhSachGiaoVienOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemGiaoVienOperationCompleted;
        
        private System.Threading.SendOrPostCallback CapNhapGiaoVienOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaGiaoVienOperationCompleted;
        
        private System.Threading.SendOrPostCallback LayDanhSachKhoiOperationCompleted;
        
        private System.Threading.SendOrPostCallback LayDanhSachLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback CapNhapLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback LayThongTinPhuHuynhOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemPhuHuynhOperationCompleted;
        
        private System.Threading.SendOrPostCallback CapNhapPhuHuynhOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaPhuHuynhOperationCompleted;
        
        private System.Threading.SendOrPostCallback LayThongTinSucKhoeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemSucKhoeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CapNhapSucKhoeOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaSucKhoeOperationCompleted;
        
        private System.Threading.SendOrPostCallback LayDanhSachTreOperationCompleted;
        
        private System.Threading.SendOrPostCallback LayDSTreTheoLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemTreOperationCompleted;
        
        private System.Threading.SendOrPostCallback CapNhapTreOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaTreOperationCompleted;
        
        private System.Threading.SendOrPostCallback LayThongTinTruongOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuaThongTinTruongOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::RemoteObjectEngine.Properties.Settings.Default.RemoteObjectEngine_nvvQLTMN_BUS_WS_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LayDanhSachGiaoVienCompletedEventHandler LayDanhSachGiaoVienCompleted;
        
        /// <remarks/>
        public event ThemGiaoVienCompletedEventHandler ThemGiaoVienCompleted;
        
        /// <remarks/>
        public event CapNhapGiaoVienCompletedEventHandler CapNhapGiaoVienCompleted;
        
        /// <remarks/>
        public event XoaGiaoVienCompletedEventHandler XoaGiaoVienCompleted;
        
        /// <remarks/>
        public event LayDanhSachKhoiCompletedEventHandler LayDanhSachKhoiCompleted;
        
        /// <remarks/>
        public event LayDanhSachLopCompletedEventHandler LayDanhSachLopCompleted;
        
        /// <remarks/>
        public event ThemLopCompletedEventHandler ThemLopCompleted;
        
        /// <remarks/>
        public event CapNhapLopCompletedEventHandler CapNhapLopCompleted;
        
        /// <remarks/>
        public event XoaLopCompletedEventHandler XoaLopCompleted;
        
        /// <remarks/>
        public event LayThongTinPhuHuynhCompletedEventHandler LayThongTinPhuHuynhCompleted;
        
        /// <remarks/>
        public event ThemPhuHuynhCompletedEventHandler ThemPhuHuynhCompleted;
        
        /// <remarks/>
        public event CapNhapPhuHuynhCompletedEventHandler CapNhapPhuHuynhCompleted;
        
        /// <remarks/>
        public event XoaPhuHuynhCompletedEventHandler XoaPhuHuynhCompleted;
        
        /// <remarks/>
        public event LayThongTinSucKhoeCompletedEventHandler LayThongTinSucKhoeCompleted;
        
        /// <remarks/>
        public event ThemSucKhoeCompletedEventHandler ThemSucKhoeCompleted;
        
        /// <remarks/>
        public event CapNhapSucKhoeCompletedEventHandler CapNhapSucKhoeCompleted;
        
        /// <remarks/>
        public event XoaSucKhoeCompletedEventHandler XoaSucKhoeCompleted;
        
        /// <remarks/>
        public event LayDanhSachTreCompletedEventHandler LayDanhSachTreCompleted;
        
        /// <remarks/>
        public event LayDSTreTheoLopCompletedEventHandler LayDSTreTheoLopCompleted;
        
        /// <remarks/>
        public event ThemTreCompletedEventHandler ThemTreCompleted;
        
        /// <remarks/>
        public event CapNhapTreCompletedEventHandler CapNhapTreCompleted;
        
        /// <remarks/>
        public event XoaTreCompletedEventHandler XoaTreCompleted;
        
        /// <remarks/>
        public event LayThongTinTruongCompletedEventHandler LayThongTinTruongCompleted;
        
        /// <remarks/>
        public event SuaThongTinTruongCompletedEventHandler SuaThongTinTruongCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayDanhSachGiaoVien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GiaoVienDTO[] LayDanhSachGiaoVien() {
            object[] results = this.Invoke("LayDanhSachGiaoVien", new object[0]);
            return ((GiaoVienDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void LayDanhSachGiaoVienAsync() {
            this.LayDanhSachGiaoVienAsync(null);
        }
        
        /// <remarks/>
        public void LayDanhSachGiaoVienAsync(object userState) {
            if ((this.LayDanhSachGiaoVienOperationCompleted == null)) {
                this.LayDanhSachGiaoVienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayDanhSachGiaoVienOperationCompleted);
            }
            this.InvokeAsync("LayDanhSachGiaoVien", new object[0], this.LayDanhSachGiaoVienOperationCompleted, userState);
        }
        
        private void OnLayDanhSachGiaoVienOperationCompleted(object arg) {
            if ((this.LayDanhSachGiaoVienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayDanhSachGiaoVienCompleted(this, new LayDanhSachGiaoVienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemGiaoVien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ThemGiaoVien(GiaoVienDTO gvtam) {
            object[] results = this.Invoke("ThemGiaoVien", new object[] {
                        gvtam});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ThemGiaoVienAsync(GiaoVienDTO gvtam) {
            this.ThemGiaoVienAsync(gvtam, null);
        }
        
        /// <remarks/>
        public void ThemGiaoVienAsync(GiaoVienDTO gvtam, object userState) {
            if ((this.ThemGiaoVienOperationCompleted == null)) {
                this.ThemGiaoVienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemGiaoVienOperationCompleted);
            }
            this.InvokeAsync("ThemGiaoVien", new object[] {
                        gvtam}, this.ThemGiaoVienOperationCompleted, userState);
        }
        
        private void OnThemGiaoVienOperationCompleted(object arg) {
            if ((this.ThemGiaoVienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemGiaoVienCompleted(this, new ThemGiaoVienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CapNhapGiaoVien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CapNhapGiaoVien(GiaoVienDTO gvtam) {
            object[] results = this.Invoke("CapNhapGiaoVien", new object[] {
                        gvtam});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CapNhapGiaoVienAsync(GiaoVienDTO gvtam) {
            this.CapNhapGiaoVienAsync(gvtam, null);
        }
        
        /// <remarks/>
        public void CapNhapGiaoVienAsync(GiaoVienDTO gvtam, object userState) {
            if ((this.CapNhapGiaoVienOperationCompleted == null)) {
                this.CapNhapGiaoVienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCapNhapGiaoVienOperationCompleted);
            }
            this.InvokeAsync("CapNhapGiaoVien", new object[] {
                        gvtam}, this.CapNhapGiaoVienOperationCompleted, userState);
        }
        
        private void OnCapNhapGiaoVienOperationCompleted(object arg) {
            if ((this.CapNhapGiaoVienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CapNhapGiaoVienCompleted(this, new CapNhapGiaoVienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaGiaoVien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool XoaGiaoVien(GiaoVienDTO gvtam) {
            object[] results = this.Invoke("XoaGiaoVien", new object[] {
                        gvtam});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void XoaGiaoVienAsync(GiaoVienDTO gvtam) {
            this.XoaGiaoVienAsync(gvtam, null);
        }
        
        /// <remarks/>
        public void XoaGiaoVienAsync(GiaoVienDTO gvtam, object userState) {
            if ((this.XoaGiaoVienOperationCompleted == null)) {
                this.XoaGiaoVienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaGiaoVienOperationCompleted);
            }
            this.InvokeAsync("XoaGiaoVien", new object[] {
                        gvtam}, this.XoaGiaoVienOperationCompleted, userState);
        }
        
        private void OnXoaGiaoVienOperationCompleted(object arg) {
            if ((this.XoaGiaoVienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaGiaoVienCompleted(this, new XoaGiaoVienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayDanhSachKhoi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KhoiDTO[] LayDanhSachKhoi() {
            object[] results = this.Invoke("LayDanhSachKhoi", new object[0]);
            return ((KhoiDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void LayDanhSachKhoiAsync() {
            this.LayDanhSachKhoiAsync(null);
        }
        
        /// <remarks/>
        public void LayDanhSachKhoiAsync(object userState) {
            if ((this.LayDanhSachKhoiOperationCompleted == null)) {
                this.LayDanhSachKhoiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayDanhSachKhoiOperationCompleted);
            }
            this.InvokeAsync("LayDanhSachKhoi", new object[0], this.LayDanhSachKhoiOperationCompleted, userState);
        }
        
        private void OnLayDanhSachKhoiOperationCompleted(object arg) {
            if ((this.LayDanhSachKhoiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayDanhSachKhoiCompleted(this, new LayDanhSachKhoiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayDanhSachLop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LopDTO[] LayDanhSachLop() {
            object[] results = this.Invoke("LayDanhSachLop", new object[0]);
            return ((LopDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void LayDanhSachLopAsync() {
            this.LayDanhSachLopAsync(null);
        }
        
        /// <remarks/>
        public void LayDanhSachLopAsync(object userState) {
            if ((this.LayDanhSachLopOperationCompleted == null)) {
                this.LayDanhSachLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayDanhSachLopOperationCompleted);
            }
            this.InvokeAsync("LayDanhSachLop", new object[0], this.LayDanhSachLopOperationCompleted, userState);
        }
        
        private void OnLayDanhSachLopOperationCompleted(object arg) {
            if ((this.LayDanhSachLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayDanhSachLopCompleted(this, new LayDanhSachLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemLop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ThemLop(LopDTO loptam) {
            object[] results = this.Invoke("ThemLop", new object[] {
                        loptam});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ThemLopAsync(LopDTO loptam) {
            this.ThemLopAsync(loptam, null);
        }
        
        /// <remarks/>
        public void ThemLopAsync(LopDTO loptam, object userState) {
            if ((this.ThemLopOperationCompleted == null)) {
                this.ThemLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemLopOperationCompleted);
            }
            this.InvokeAsync("ThemLop", new object[] {
                        loptam}, this.ThemLopOperationCompleted, userState);
        }
        
        private void OnThemLopOperationCompleted(object arg) {
            if ((this.ThemLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemLopCompleted(this, new ThemLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CapNhapLop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CapNhapLop(LopDTO loptam) {
            object[] results = this.Invoke("CapNhapLop", new object[] {
                        loptam});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CapNhapLopAsync(LopDTO loptam) {
            this.CapNhapLopAsync(loptam, null);
        }
        
        /// <remarks/>
        public void CapNhapLopAsync(LopDTO loptam, object userState) {
            if ((this.CapNhapLopOperationCompleted == null)) {
                this.CapNhapLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCapNhapLopOperationCompleted);
            }
            this.InvokeAsync("CapNhapLop", new object[] {
                        loptam}, this.CapNhapLopOperationCompleted, userState);
        }
        
        private void OnCapNhapLopOperationCompleted(object arg) {
            if ((this.CapNhapLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CapNhapLopCompleted(this, new CapNhapLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaLop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool XoaLop(LopDTO loptam) {
            object[] results = this.Invoke("XoaLop", new object[] {
                        loptam});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void XoaLopAsync(LopDTO loptam) {
            this.XoaLopAsync(loptam, null);
        }
        
        /// <remarks/>
        public void XoaLopAsync(LopDTO loptam, object userState) {
            if ((this.XoaLopOperationCompleted == null)) {
                this.XoaLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaLopOperationCompleted);
            }
            this.InvokeAsync("XoaLop", new object[] {
                        loptam}, this.XoaLopOperationCompleted, userState);
        }
        
        private void OnXoaLopOperationCompleted(object arg) {
            if ((this.XoaLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaLopCompleted(this, new XoaLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayThongTinPhuHuynh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhuHuynhDTO[] LayThongTinPhuHuynh(int maphuhuynh) {
            object[] results = this.Invoke("LayThongTinPhuHuynh", new object[] {
                        maphuhuynh});
            return ((PhuHuynhDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void LayThongTinPhuHuynhAsync(int maphuhuynh) {
            this.LayThongTinPhuHuynhAsync(maphuhuynh, null);
        }
        
        /// <remarks/>
        public void LayThongTinPhuHuynhAsync(int maphuhuynh, object userState) {
            if ((this.LayThongTinPhuHuynhOperationCompleted == null)) {
                this.LayThongTinPhuHuynhOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayThongTinPhuHuynhOperationCompleted);
            }
            this.InvokeAsync("LayThongTinPhuHuynh", new object[] {
                        maphuhuynh}, this.LayThongTinPhuHuynhOperationCompleted, userState);
        }
        
        private void OnLayThongTinPhuHuynhOperationCompleted(object arg) {
            if ((this.LayThongTinPhuHuynhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayThongTinPhuHuynhCompleted(this, new LayThongTinPhuHuynhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemPhuHuynh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ThemPhuHuynh(PhuHuynhDTO phuhuynh) {
            object[] results = this.Invoke("ThemPhuHuynh", new object[] {
                        phuhuynh});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ThemPhuHuynhAsync(PhuHuynhDTO phuhuynh) {
            this.ThemPhuHuynhAsync(phuhuynh, null);
        }
        
        /// <remarks/>
        public void ThemPhuHuynhAsync(PhuHuynhDTO phuhuynh, object userState) {
            if ((this.ThemPhuHuynhOperationCompleted == null)) {
                this.ThemPhuHuynhOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemPhuHuynhOperationCompleted);
            }
            this.InvokeAsync("ThemPhuHuynh", new object[] {
                        phuhuynh}, this.ThemPhuHuynhOperationCompleted, userState);
        }
        
        private void OnThemPhuHuynhOperationCompleted(object arg) {
            if ((this.ThemPhuHuynhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemPhuHuynhCompleted(this, new ThemPhuHuynhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CapNhapPhuHuynh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CapNhapPhuHuynh(PhuHuynhDTO phuhuynh) {
            object[] results = this.Invoke("CapNhapPhuHuynh", new object[] {
                        phuhuynh});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CapNhapPhuHuynhAsync(PhuHuynhDTO phuhuynh) {
            this.CapNhapPhuHuynhAsync(phuhuynh, null);
        }
        
        /// <remarks/>
        public void CapNhapPhuHuynhAsync(PhuHuynhDTO phuhuynh, object userState) {
            if ((this.CapNhapPhuHuynhOperationCompleted == null)) {
                this.CapNhapPhuHuynhOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCapNhapPhuHuynhOperationCompleted);
            }
            this.InvokeAsync("CapNhapPhuHuynh", new object[] {
                        phuhuynh}, this.CapNhapPhuHuynhOperationCompleted, userState);
        }
        
        private void OnCapNhapPhuHuynhOperationCompleted(object arg) {
            if ((this.CapNhapPhuHuynhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CapNhapPhuHuynhCompleted(this, new CapNhapPhuHuynhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaPhuHuynh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool XoaPhuHuynh(int maPH) {
            object[] results = this.Invoke("XoaPhuHuynh", new object[] {
                        maPH});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void XoaPhuHuynhAsync(int maPH) {
            this.XoaPhuHuynhAsync(maPH, null);
        }
        
        /// <remarks/>
        public void XoaPhuHuynhAsync(int maPH, object userState) {
            if ((this.XoaPhuHuynhOperationCompleted == null)) {
                this.XoaPhuHuynhOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaPhuHuynhOperationCompleted);
            }
            this.InvokeAsync("XoaPhuHuynh", new object[] {
                        maPH}, this.XoaPhuHuynhOperationCompleted, userState);
        }
        
        private void OnXoaPhuHuynhOperationCompleted(object arg) {
            if ((this.XoaPhuHuynhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaPhuHuynhCompleted(this, new XoaPhuHuynhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayThongTinSucKhoe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TinhTrangSucKhoeDTO[] LayThongTinSucKhoe(int masuckhoe) {
            object[] results = this.Invoke("LayThongTinSucKhoe", new object[] {
                        masuckhoe});
            return ((TinhTrangSucKhoeDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void LayThongTinSucKhoeAsync(int masuckhoe) {
            this.LayThongTinSucKhoeAsync(masuckhoe, null);
        }
        
        /// <remarks/>
        public void LayThongTinSucKhoeAsync(int masuckhoe, object userState) {
            if ((this.LayThongTinSucKhoeOperationCompleted == null)) {
                this.LayThongTinSucKhoeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayThongTinSucKhoeOperationCompleted);
            }
            this.InvokeAsync("LayThongTinSucKhoe", new object[] {
                        masuckhoe}, this.LayThongTinSucKhoeOperationCompleted, userState);
        }
        
        private void OnLayThongTinSucKhoeOperationCompleted(object arg) {
            if ((this.LayThongTinSucKhoeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayThongTinSucKhoeCompleted(this, new LayThongTinSucKhoeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemSucKhoe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ThemSucKhoe(TinhTrangSucKhoeDTO suckhoe) {
            object[] results = this.Invoke("ThemSucKhoe", new object[] {
                        suckhoe});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ThemSucKhoeAsync(TinhTrangSucKhoeDTO suckhoe) {
            this.ThemSucKhoeAsync(suckhoe, null);
        }
        
        /// <remarks/>
        public void ThemSucKhoeAsync(TinhTrangSucKhoeDTO suckhoe, object userState) {
            if ((this.ThemSucKhoeOperationCompleted == null)) {
                this.ThemSucKhoeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemSucKhoeOperationCompleted);
            }
            this.InvokeAsync("ThemSucKhoe", new object[] {
                        suckhoe}, this.ThemSucKhoeOperationCompleted, userState);
        }
        
        private void OnThemSucKhoeOperationCompleted(object arg) {
            if ((this.ThemSucKhoeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemSucKhoeCompleted(this, new ThemSucKhoeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CapNhapSucKhoe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CapNhapSucKhoe(TinhTrangSucKhoeDTO suckhoe) {
            object[] results = this.Invoke("CapNhapSucKhoe", new object[] {
                        suckhoe});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CapNhapSucKhoeAsync(TinhTrangSucKhoeDTO suckhoe) {
            this.CapNhapSucKhoeAsync(suckhoe, null);
        }
        
        /// <remarks/>
        public void CapNhapSucKhoeAsync(TinhTrangSucKhoeDTO suckhoe, object userState) {
            if ((this.CapNhapSucKhoeOperationCompleted == null)) {
                this.CapNhapSucKhoeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCapNhapSucKhoeOperationCompleted);
            }
            this.InvokeAsync("CapNhapSucKhoe", new object[] {
                        suckhoe}, this.CapNhapSucKhoeOperationCompleted, userState);
        }
        
        private void OnCapNhapSucKhoeOperationCompleted(object arg) {
            if ((this.CapNhapSucKhoeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CapNhapSucKhoeCompleted(this, new CapNhapSucKhoeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaSucKhoe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool XoaSucKhoe(int maSk) {
            object[] results = this.Invoke("XoaSucKhoe", new object[] {
                        maSk});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void XoaSucKhoeAsync(int maSk) {
            this.XoaSucKhoeAsync(maSk, null);
        }
        
        /// <remarks/>
        public void XoaSucKhoeAsync(int maSk, object userState) {
            if ((this.XoaSucKhoeOperationCompleted == null)) {
                this.XoaSucKhoeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaSucKhoeOperationCompleted);
            }
            this.InvokeAsync("XoaSucKhoe", new object[] {
                        maSk}, this.XoaSucKhoeOperationCompleted, userState);
        }
        
        private void OnXoaSucKhoeOperationCompleted(object arg) {
            if ((this.XoaSucKhoeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaSucKhoeCompleted(this, new XoaSucKhoeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayDanhSachTre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TreDTO[] LayDanhSachTre() {
            object[] results = this.Invoke("LayDanhSachTre", new object[0]);
            return ((TreDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void LayDanhSachTreAsync() {
            this.LayDanhSachTreAsync(null);
        }
        
        /// <remarks/>
        public void LayDanhSachTreAsync(object userState) {
            if ((this.LayDanhSachTreOperationCompleted == null)) {
                this.LayDanhSachTreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayDanhSachTreOperationCompleted);
            }
            this.InvokeAsync("LayDanhSachTre", new object[0], this.LayDanhSachTreOperationCompleted, userState);
        }
        
        private void OnLayDanhSachTreOperationCompleted(object arg) {
            if ((this.LayDanhSachTreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayDanhSachTreCompleted(this, new LayDanhSachTreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayDSTreTheoLop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TreDTO[] LayDSTreTheoLop(string tenlop) {
            object[] results = this.Invoke("LayDSTreTheoLop", new object[] {
                        tenlop});
            return ((TreDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void LayDSTreTheoLopAsync(string tenlop) {
            this.LayDSTreTheoLopAsync(tenlop, null);
        }
        
        /// <remarks/>
        public void LayDSTreTheoLopAsync(string tenlop, object userState) {
            if ((this.LayDSTreTheoLopOperationCompleted == null)) {
                this.LayDSTreTheoLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayDSTreTheoLopOperationCompleted);
            }
            this.InvokeAsync("LayDSTreTheoLop", new object[] {
                        tenlop}, this.LayDSTreTheoLopOperationCompleted, userState);
        }
        
        private void OnLayDSTreTheoLopOperationCompleted(object arg) {
            if ((this.LayDSTreTheoLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayDSTreTheoLopCompleted(this, new LayDSTreTheoLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemTre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ThemTre(TreDTO tretam) {
            object[] results = this.Invoke("ThemTre", new object[] {
                        tretam});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ThemTreAsync(TreDTO tretam) {
            this.ThemTreAsync(tretam, null);
        }
        
        /// <remarks/>
        public void ThemTreAsync(TreDTO tretam, object userState) {
            if ((this.ThemTreOperationCompleted == null)) {
                this.ThemTreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemTreOperationCompleted);
            }
            this.InvokeAsync("ThemTre", new object[] {
                        tretam}, this.ThemTreOperationCompleted, userState);
        }
        
        private void OnThemTreOperationCompleted(object arg) {
            if ((this.ThemTreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemTreCompleted(this, new ThemTreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CapNhapTre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CapNhapTre(TreDTO tretam) {
            object[] results = this.Invoke("CapNhapTre", new object[] {
                        tretam});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CapNhapTreAsync(TreDTO tretam) {
            this.CapNhapTreAsync(tretam, null);
        }
        
        /// <remarks/>
        public void CapNhapTreAsync(TreDTO tretam, object userState) {
            if ((this.CapNhapTreOperationCompleted == null)) {
                this.CapNhapTreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCapNhapTreOperationCompleted);
            }
            this.InvokeAsync("CapNhapTre", new object[] {
                        tretam}, this.CapNhapTreOperationCompleted, userState);
        }
        
        private void OnCapNhapTreOperationCompleted(object arg) {
            if ((this.CapNhapTreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CapNhapTreCompleted(this, new CapNhapTreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaTre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool XoaTre(TreDTO tretam) {
            object[] results = this.Invoke("XoaTre", new object[] {
                        tretam});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void XoaTreAsync(TreDTO tretam) {
            this.XoaTreAsync(tretam, null);
        }
        
        /// <remarks/>
        public void XoaTreAsync(TreDTO tretam, object userState) {
            if ((this.XoaTreOperationCompleted == null)) {
                this.XoaTreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaTreOperationCompleted);
            }
            this.InvokeAsync("XoaTre", new object[] {
                        tretam}, this.XoaTreOperationCompleted, userState);
        }
        
        private void OnXoaTreOperationCompleted(object arg) {
            if ((this.XoaTreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaTreCompleted(this, new XoaTreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayThongTinTruong", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TruongDTO LayThongTinTruong() {
            object[] results = this.Invoke("LayThongTinTruong", new object[0]);
            return ((TruongDTO)(results[0]));
        }
        
        /// <remarks/>
        public void LayThongTinTruongAsync() {
            this.LayThongTinTruongAsync(null);
        }
        
        /// <remarks/>
        public void LayThongTinTruongAsync(object userState) {
            if ((this.LayThongTinTruongOperationCompleted == null)) {
                this.LayThongTinTruongOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayThongTinTruongOperationCompleted);
            }
            this.InvokeAsync("LayThongTinTruong", new object[0], this.LayThongTinTruongOperationCompleted, userState);
        }
        
        private void OnLayThongTinTruongOperationCompleted(object arg) {
            if ((this.LayThongTinTruongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayThongTinTruongCompleted(this, new LayThongTinTruongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuaThongTinTruong", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SuaThongTinTruong(TruongDTO truonghoc) {
            object[] results = this.Invoke("SuaThongTinTruong", new object[] {
                        truonghoc});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SuaThongTinTruongAsync(TruongDTO truonghoc) {
            this.SuaThongTinTruongAsync(truonghoc, null);
        }
        
        /// <remarks/>
        public void SuaThongTinTruongAsync(TruongDTO truonghoc, object userState) {
            if ((this.SuaThongTinTruongOperationCompleted == null)) {
                this.SuaThongTinTruongOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuaThongTinTruongOperationCompleted);
            }
            this.InvokeAsync("SuaThongTinTruong", new object[] {
                        truonghoc}, this.SuaThongTinTruongOperationCompleted, userState);
        }
        
        private void OnSuaThongTinTruongOperationCompleted(object arg) {
            if ((this.SuaThongTinTruongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuaThongTinTruongCompleted(this, new SuaThongTinTruongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GiaoVienDTO {
        
        private int maGiaoVienField;
        
        private string tenGiaoVienField;
        
        private string gioiTinhField;
        
        private string diaChiField;
        
        private System.DateTime ngaySinhField;
        
        private string soDienThoaiField;
        
        private string chucVuField;
        
        private string bangCapField;
        
        private string luongField;
        
        private string tenLopPhuTrachField;
        
        /// <remarks/>
        public int MaGiaoVien {
            get {
                return this.maGiaoVienField;
            }
            set {
                this.maGiaoVienField = value;
            }
        }
        
        /// <remarks/>
        public string TenGiaoVien {
            get {
                return this.tenGiaoVienField;
            }
            set {
                this.tenGiaoVienField = value;
            }
        }
        
        /// <remarks/>
        public string GioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                this.gioiTinhField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                this.ngaySinhField = value;
            }
        }
        
        /// <remarks/>
        public string SoDienThoai {
            get {
                return this.soDienThoaiField;
            }
            set {
                this.soDienThoaiField = value;
            }
        }
        
        /// <remarks/>
        public string ChucVu {
            get {
                return this.chucVuField;
            }
            set {
                this.chucVuField = value;
            }
        }
        
        /// <remarks/>
        public string BangCap {
            get {
                return this.bangCapField;
            }
            set {
                this.bangCapField = value;
            }
        }
        
        /// <remarks/>
        public string Luong {
            get {
                return this.luongField;
            }
            set {
                this.luongField = value;
            }
        }
        
        /// <remarks/>
        public string TenLopPhuTrach {
            get {
                return this.tenLopPhuTrachField;
            }
            set {
                this.tenLopPhuTrachField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TruongDTO {
        
        private int maTruongField;
        
        private string tenTruongField;
        
        private string diaChiField;
        
        private string sdtField;
        
        /// <remarks/>
        public int MaTruong {
            get {
                return this.maTruongField;
            }
            set {
                this.maTruongField = value;
            }
        }
        
        /// <remarks/>
        public string TenTruong {
            get {
                return this.tenTruongField;
            }
            set {
                this.tenTruongField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
            }
        }
        
        /// <remarks/>
        public string Sdt {
            get {
                return this.sdtField;
            }
            set {
                this.sdtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TreDTO {
        
        private int maTreField;
        
        private string hoTenField;
        
        private string gioiTinhField;
        
        private System.DateTime ngaySinhField;
        
        private int conThuField;
        
        private string tenLopField;
        
        private int maTinhTrangSucKhoeField;
        
        private int maPhuHuynhField;
        
        /// <remarks/>
        public int MaTre {
            get {
                return this.maTreField;
            }
            set {
                this.maTreField = value;
            }
        }
        
        /// <remarks/>
        public string HoTen {
            get {
                return this.hoTenField;
            }
            set {
                this.hoTenField = value;
            }
        }
        
        /// <remarks/>
        public string GioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                this.gioiTinhField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                this.ngaySinhField = value;
            }
        }
        
        /// <remarks/>
        public int ConThu {
            get {
                return this.conThuField;
            }
            set {
                this.conThuField = value;
            }
        }
        
        /// <remarks/>
        public string TenLop {
            get {
                return this.tenLopField;
            }
            set {
                this.tenLopField = value;
            }
        }
        
        /// <remarks/>
        public int MaTinhTrangSucKhoe {
            get {
                return this.maTinhTrangSucKhoeField;
            }
            set {
                this.maTinhTrangSucKhoeField = value;
            }
        }
        
        /// <remarks/>
        public int MaPhuHuynh {
            get {
                return this.maPhuHuynhField;
            }
            set {
                this.maPhuHuynhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TinhTrangSucKhoeDTO {
        
        private int maTinhTrangSucKhoeField;
        
        private float canNangField;
        
        private float chieuCaoField;
        
        private string benhDiTruyenField;
        
        private string dinhDuongField;
        
        private string daNiemMacField;
        
        private string duongHoHapField;
        
        private string heTimMachField;
        
        private string taiMuiHongField;
        
        private string matField;
        
        private string rangHamMatField;
        
        private string tiemNguaField;
        
        /// <remarks/>
        public int MaTinhTrangSucKhoe {
            get {
                return this.maTinhTrangSucKhoeField;
            }
            set {
                this.maTinhTrangSucKhoeField = value;
            }
        }
        
        /// <remarks/>
        public float CanNang {
            get {
                return this.canNangField;
            }
            set {
                this.canNangField = value;
            }
        }
        
        /// <remarks/>
        public float ChieuCao {
            get {
                return this.chieuCaoField;
            }
            set {
                this.chieuCaoField = value;
            }
        }
        
        /// <remarks/>
        public string BenhDiTruyen {
            get {
                return this.benhDiTruyenField;
            }
            set {
                this.benhDiTruyenField = value;
            }
        }
        
        /// <remarks/>
        public string DinhDuong {
            get {
                return this.dinhDuongField;
            }
            set {
                this.dinhDuongField = value;
            }
        }
        
        /// <remarks/>
        public string DaNiemMac {
            get {
                return this.daNiemMacField;
            }
            set {
                this.daNiemMacField = value;
            }
        }
        
        /// <remarks/>
        public string DuongHoHap {
            get {
                return this.duongHoHapField;
            }
            set {
                this.duongHoHapField = value;
            }
        }
        
        /// <remarks/>
        public string HeTimMach {
            get {
                return this.heTimMachField;
            }
            set {
                this.heTimMachField = value;
            }
        }
        
        /// <remarks/>
        public string TaiMuiHong {
            get {
                return this.taiMuiHongField;
            }
            set {
                this.taiMuiHongField = value;
            }
        }
        
        /// <remarks/>
        public string Mat {
            get {
                return this.matField;
            }
            set {
                this.matField = value;
            }
        }
        
        /// <remarks/>
        public string RangHamMat {
            get {
                return this.rangHamMatField;
            }
            set {
                this.rangHamMatField = value;
            }
        }
        
        /// <remarks/>
        public string TiemNgua {
            get {
                return this.tiemNguaField;
            }
            set {
                this.tiemNguaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PhuHuynhDTO {
        
        private int maPhuHuynhField;
        
        private string tenChaField;
        
        private string ngheNghiepChaField;
        
        private int tuoiChaField;
        
        private string sdtChaField;
        
        private string diaChiCoQuanChaField;
        
        private string tenMeField;
        
        private string ngheNghiepMeField;
        
        private int tuoiMeField;
        
        private string sdtMeField;
        
        private string diaChiCoQuanMeField;
        
        /// <remarks/>
        public int MaPhuHuynh {
            get {
                return this.maPhuHuynhField;
            }
            set {
                this.maPhuHuynhField = value;
            }
        }
        
        /// <remarks/>
        public string TenCha {
            get {
                return this.tenChaField;
            }
            set {
                this.tenChaField = value;
            }
        }
        
        /// <remarks/>
        public string NgheNghiepCha {
            get {
                return this.ngheNghiepChaField;
            }
            set {
                this.ngheNghiepChaField = value;
            }
        }
        
        /// <remarks/>
        public int TuoiCha {
            get {
                return this.tuoiChaField;
            }
            set {
                this.tuoiChaField = value;
            }
        }
        
        /// <remarks/>
        public string SdtCha {
            get {
                return this.sdtChaField;
            }
            set {
                this.sdtChaField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChiCoQuanCha {
            get {
                return this.diaChiCoQuanChaField;
            }
            set {
                this.diaChiCoQuanChaField = value;
            }
        }
        
        /// <remarks/>
        public string TenMe {
            get {
                return this.tenMeField;
            }
            set {
                this.tenMeField = value;
            }
        }
        
        /// <remarks/>
        public string NgheNghiepMe {
            get {
                return this.ngheNghiepMeField;
            }
            set {
                this.ngheNghiepMeField = value;
            }
        }
        
        /// <remarks/>
        public int TuoiMe {
            get {
                return this.tuoiMeField;
            }
            set {
                this.tuoiMeField = value;
            }
        }
        
        /// <remarks/>
        public string SdtMe {
            get {
                return this.sdtMeField;
            }
            set {
                this.sdtMeField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChiCoQuanMe {
            get {
                return this.diaChiCoQuanMeField;
            }
            set {
                this.diaChiCoQuanMeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LopDTO {
        
        private int maLopField;
        
        private string tenLopField;
        
        private string doTuoiField;
        
        private int siSoField;
        
        private string tenKhoiField;
        
        /// <remarks/>
        public int MaLop {
            get {
                return this.maLopField;
            }
            set {
                this.maLopField = value;
            }
        }
        
        /// <remarks/>
        public string TenLop {
            get {
                return this.tenLopField;
            }
            set {
                this.tenLopField = value;
            }
        }
        
        /// <remarks/>
        public string DoTuoi {
            get {
                return this.doTuoiField;
            }
            set {
                this.doTuoiField = value;
            }
        }
        
        /// <remarks/>
        public int SiSo {
            get {
                return this.siSoField;
            }
            set {
                this.siSoField = value;
            }
        }
        
        /// <remarks/>
        public string TenKhoi {
            get {
                return this.tenKhoiField;
            }
            set {
                this.tenKhoiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KhoiDTO {
        
        private int maKhoiField;
        
        private string tenKhoiField;
        
        private int soLopField;
        
        /// <remarks/>
        public int MaKhoi {
            get {
                return this.maKhoiField;
            }
            set {
                this.maKhoiField = value;
            }
        }
        
        /// <remarks/>
        public string TenKhoi {
            get {
                return this.tenKhoiField;
            }
            set {
                this.tenKhoiField = value;
            }
        }
        
        /// <remarks/>
        public int SoLop {
            get {
                return this.soLopField;
            }
            set {
                this.soLopField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LayDanhSachGiaoVienCompletedEventHandler(object sender, LayDanhSachGiaoVienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayDanhSachGiaoVienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayDanhSachGiaoVienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GiaoVienDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GiaoVienDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ThemGiaoVienCompletedEventHandler(object sender, ThemGiaoVienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemGiaoVienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemGiaoVienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CapNhapGiaoVienCompletedEventHandler(object sender, CapNhapGiaoVienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CapNhapGiaoVienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CapNhapGiaoVienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void XoaGiaoVienCompletedEventHandler(object sender, XoaGiaoVienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaGiaoVienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaGiaoVienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LayDanhSachKhoiCompletedEventHandler(object sender, LayDanhSachKhoiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayDanhSachKhoiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayDanhSachKhoiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KhoiDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KhoiDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LayDanhSachLopCompletedEventHandler(object sender, LayDanhSachLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayDanhSachLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayDanhSachLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LopDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LopDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ThemLopCompletedEventHandler(object sender, ThemLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CapNhapLopCompletedEventHandler(object sender, CapNhapLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CapNhapLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CapNhapLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void XoaLopCompletedEventHandler(object sender, XoaLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LayThongTinPhuHuynhCompletedEventHandler(object sender, LayThongTinPhuHuynhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayThongTinPhuHuynhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayThongTinPhuHuynhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhuHuynhDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhuHuynhDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ThemPhuHuynhCompletedEventHandler(object sender, ThemPhuHuynhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemPhuHuynhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemPhuHuynhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CapNhapPhuHuynhCompletedEventHandler(object sender, CapNhapPhuHuynhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CapNhapPhuHuynhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CapNhapPhuHuynhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void XoaPhuHuynhCompletedEventHandler(object sender, XoaPhuHuynhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaPhuHuynhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaPhuHuynhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LayThongTinSucKhoeCompletedEventHandler(object sender, LayThongTinSucKhoeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayThongTinSucKhoeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayThongTinSucKhoeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TinhTrangSucKhoeDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TinhTrangSucKhoeDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ThemSucKhoeCompletedEventHandler(object sender, ThemSucKhoeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemSucKhoeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemSucKhoeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CapNhapSucKhoeCompletedEventHandler(object sender, CapNhapSucKhoeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CapNhapSucKhoeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CapNhapSucKhoeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void XoaSucKhoeCompletedEventHandler(object sender, XoaSucKhoeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaSucKhoeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaSucKhoeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LayDanhSachTreCompletedEventHandler(object sender, LayDanhSachTreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayDanhSachTreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayDanhSachTreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TreDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TreDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LayDSTreTheoLopCompletedEventHandler(object sender, LayDSTreTheoLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayDSTreTheoLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayDSTreTheoLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TreDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TreDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ThemTreCompletedEventHandler(object sender, ThemTreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemTreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemTreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CapNhapTreCompletedEventHandler(object sender, CapNhapTreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CapNhapTreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CapNhapTreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void XoaTreCompletedEventHandler(object sender, XoaTreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaTreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaTreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LayThongTinTruongCompletedEventHandler(object sender, LayThongTinTruongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayThongTinTruongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayThongTinTruongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TruongDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TruongDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SuaThongTinTruongCompletedEventHandler(object sender, SuaThongTinTruongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuaThongTinTruongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuaThongTinTruongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591